---
title: "Regressions_Final"
author: "Talha Ahmad Farooqui"
date: "4/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars, include=FALSE}
library(readr)
library(fastDummies)
library(huxtable)
library(jtools)
dataf <- read_csv("~/QRFINALDATA!!.csv")
dataf2 <- dummy_cols(dataf, select_columns = c('AC1','AC2'))
ACs<- dataf2[,c(11,12:43)]
reg <- glm(IndGrd ~ ., data = ACs, family = "gaussian")
summary(reg)

AC1<- dataf2[,c(11,12:27)]
reg2 <- glm(IndGrd ~ ., data = AC1, family = "gaussian")
summary(reg2)

AC2 <- dataf2[,c(11,28:43)]
reg3 <- glm(IndGrd ~ ., data = AC2, family = "gaussian")
summary(reg3)

dataf3 <- dummy_cols(dataf, select_columns = c('Sex','Region'))
Region <- dataf3[,c(11,14:20)]
region <- glm(IndGrd ~ ., data = Region, family = "gaussian")
summary(region)


subset <-  dataf[,-c(1,4,5,7)]
all <- glm(IndGrd ~ ., data = subset, family = "gaussian")
summary(all)
summary(all)
```

```{r}
summ(reg)
summ(reg2)
summ(reg3)
summ(region)
summ(all)

library(sjPlot)
tab_model(all)
tab_model(reg3)
